# Lサイズのバックボーン一覧
# 251006時点のDBから抽出

model_name:
  # ResNet-RS
  - resnetrs152.tf_in1k
  - resnetrs200.tf_in1k

  # ResNeSt
  - resnest50d.in1k

  # ConvNeXt V1
  - convnext_base.fb_in22k_ft_in1k

  # ConvNeXt V2
  - convnextv2_base.fcmae_ft_in22k_in1k

  # ConvFormer
  - convformer_s36.sail_in22k_ft_in1k
  - convformer_m36.sail_in22k_ft_in1k

  # CAFormer
  - caformer_s36.sail_in22k_ft_in1k
  - caformer_m36.sail_in22k_ft_in1k

  # RDNet
  - rdnet_base.nv_in1k

  # InceptionNext
  - inception_next_base.sail_in1k

  # MaxViT（インプットサイズ固定）
  - maxvit_small_tf_224.in1k

  # Swin V1（インプットサイズ固定）
  - swin_base_patch4_window7_224.ms_in22k_ft_in1k

  # Swin V2（インプットサイズ固定）
  - swinv2_small_window8_256.ms_in1k
